<?php
return array(
    array(
        "label" => esc_html__("Footer columns", 'compactor'),
        "id" => "footer_column",
        "type" => "grid",
        "defaultValue" => array(
            'one_columns' => esc_html__('1 Column', 'compactor'),
            'tow_a_columns' => esc_html__('2 columns (1/2 + 1/2)', 'compactor'),
            'tow_b_columns' => esc_html__('2 columns (1/3 + 2/3)', 'compactor'),
            'tow_c_columns' => esc_html__('2 columns (2/3 + 1/3)', 'compactor'),
            'three_columns' => esc_html__('3 columns', 'compactor'),
            'four_columns' => esc_html__('4 columns', 'compactor'),
        ),
        "parentSection" => "Footer setting",
        "group" => "Footer settings",
        "description" => "",
    ),
    array(
        "label" => esc_html__("Footer background image", 'compactor'),
        "id" => "footer_bg_img",
        "type" => "imgupload",
        "defaultValue" => "",
        "parentSection" => "Footer setting",
        "group" => "Footer settings",
        "description" => "",
    ),
    array(
        "label" => esc_html__("Footer Copyright text", 'compactor'),
        "id" => "copyright_text",
        "type" => "text",
        "defaultValue" => "",
        "parentSection" => "Footer setting",
        "group" => "Footer settings",
        "description" => "",
    ),
    array(
        "label" => esc_html__("Powered by text", 'compactor'),
        "id" => "powered_text",
        "type" => "text",
        "defaultValue" => "",
        "parentSection" => "Footer setting",
        "group" => "Footer settings",
        "description" => "",
    ),
    array(
        "label" => esc_html__("social media", 'compactor'),
        "id" => "",
        "type" => "socialmedia",
        "defaultValue" => "",
        "parentSection" => "Footer setting",
        "group" => "Footer settings",
        "description" => "",
    ),
);