<?php
return array(
    array(
        "label" => esc_html__('Boxed Layout', 'compactor'),
        "id" => "boxed_layout",
        "type" => "checkbox",
        "defaultValue" => WD_BOXED_LAYOUT,
        "parentSection" => "General Settings",
        "group" => "General Settings",
        "description" => esc_html__("The boxed layout has a padding around the main wrapper", 'compactor'),
    ),
    array(
        "label" => esc_html__("Menu style", 'compactor'),
        "id" => "menu_style",
        "type" => "dropdown",
        "defaultValue" => array("Corporate" => "corporate", "Creative" => "creative"),
        "parentSection" => "General Settings",
        "group" => "General Settings",
        "description" => esc_html__("Collection of styles to customize the Menu", 'compactor'),
    ),
    array(
        "label" => esc_html__("Menu Mobile layout", 'compactor'),
        "id" => "menu_mobile_layout",
        "type" => "checkbox",
        "defaultValue" => WD_MENU_MOBILE_LAYOUT,
        "parentSection" => "General Settings",
        "group" => "General Settings",
        "description" => esc_html__("collection of styles to customize the Menu", 'compactor'),
    ),
    array(
        "label" => esc_html__("Limit header width to grid layout", 'compactor'),
        "id" => "header_contain_to_grid",
        "type" => "checkbox",
        "defaultValue" => WD_HEADER_CONTAIN_TO_GRID,
        "parentSection" => "General Settings",
        "group" => "General Settings",
        "description" => esc_html__("Make header in grid", 'compactor'),
    ),
    array(
        "label" => esc_html__("Stick the menu to Top", 'compactor'),
        "id" => "stick_menu_to_top",
        "type" => "checkbox",
        "defaultValue" => WD_STICK_MENU_TO_TOP,
        "parentSection" => "General Settings",
        "group" => "General Settings",
        "description" => esc_html__("Fixed menu in top on scroll", 'compactor'),
    ),
    array(
        "label" => esc_html__("Page Loading Animation", 'compactor'),
        "id" => "page_loading_animation",
        "type" => "checkbox",
        "defaultValue" => WD_PAGE_LOADING_ANIMATION,
        "parentSection" => "General Settings",
        "group" => "General Settings",
        "description" => esc_html__("Add page preloader animation ", 'compactor'),
    ),

    array(
        "label" => esc_html__("Show Social Top bare", 'compactor'),
        "id" => "show_top_social_bare",
        "type" => "checkbox",
        "defaultValue" => SHOW_TOP_SOCIAL_BARE,
        "parentSection" => "General Settings",
        "group" => "General Settings",
        "description" => esc_html__("Show social icon bar befor nav bar", 'compactor'),
    ),

    array(
        "label" => esc_html__("Show Search Icon", 'compactor'),
        "id" => "show_search_icon",
        "type" => "checkbox",
        "defaultValue" => SHOW_SEARCH_ICON,
        "parentSection" => "General Settings",
        "group" => "General Settings",
        "description" => esc_html__("Show seach icon and search form in the header", 'compactor'),
    ),


    array(
        "label" => esc_html__("Call to Action Button", 'compactor'),
        "id" => "action_button",
        "type" => "textarea",
        "defaultValue" => "",
        "parentSection" => "General Settings",
        "group" => "General Settings",
        "description" => esc_html__("The content of call action button in header", 'compactor'),
    ),
    array(
        "label" => esc_html__("Find out more Button", 'compactor'),
        "id" => "find_out_more",
        "type" => "textarea",
        "defaultValue" => "",
        "parentSection" => "General Settings",
        "group" => "General Settings",
        "description" => esc_html__("Add more button using html markup", 'compactor'),
    ),
    array(
        "label" => esc_html__("Body Background image", 'compactor'),
        "id" => "body_background_image",
        "type" => "imgupload",
        "defaultValue" => "",
        "parentSection" => "General Settings",
        "group" => "General Settings",
        "description" => esc_html__("The main wrapper image, when we have a boxed layout", 'compactor'),
    ),
    array(
        "label" => esc_html__("Show the Logo", 'compactor'),
        "id" => "show_the_logo",
        "type" => "checkbox",
        "defaultValue" => WD_SHOW_THE_LOGO,
        "parentSection" => "General Settings",
        "group" => "Logo Settings",
        "description" => esc_html__("", 'compactor'),
    ),
    array(
        "label" => esc_html__("Show Website Title", 'compactor'),
        "id" => "show_website_title",
        "type" => "checkbox",
        "defaultValue" => WD_SHOW_WEBSITE_TITLE,
        "parentSection" => "General Settings",
        "group" => "Logo Settings",
        "description" => esc_html__("", 'compactor'),
    ),
    array(
        "label" => esc_html__("Logo link", 'compactor'),
        "id" => "logo_link",
        "type" => "imgupload",
        "defaultValue" => "Logo link",
        "parentSection" => "General Settings",
        "group" => "Logo Settings",
        "description" => esc_html__("The logo link using wordpress library", 'compactor'),
    ),
    array(
        "label" => esc_html__("Logo Height", 'compactor'),
        "id" => "logo_height",
        "type" => "text",
        "defaultValue" => "",
        "parentSection" => "General Settings",
        "group" => "Logo Settings",
        "description" => esc_html__("Fixed max height logo", 'compactor'),
    ),
    array(
        "label" => esc_html__("Logo Padding", 'compactor'),
        "id" => "logo_padding",
        "type" => "text",
        "defaultValue" => "",
        "parentSection" => "General Settings",
        "group" => "Logo Settings",
        "description" => esc_html__("Add padding to logo ex: 10px 10px 10px 10px", 'compactor'),
    ),
    array(
        "label" => esc_html__("Google Key Map", 'compactor'),
        "id" => "google_key_map",
        "type" => "text",
        "defaultValue" => "Google Key Map",
        "parentSection" => "General Settings",
        "group" => "Page Settings",
        "description" => esc_html__("Generate your key maps from google API and pasted here", 'compactor'),
    ),
    array(
        "label" => esc_html__("Title Bar background image", 'compactor'),
        "id" => "title_page_bg",
        "type" => "text",
        "defaultValue" => "Default Title Bar background image",
        "parentSection" => "General Settings",
        "group" => "Page Settings",
        "description" => esc_html__("Change your default title bar using wordpress library", 'compactor'),
    ),

	array(
		"label" => esc_html__("Address", 'compactor'),
		"id" => "head_info_address",
		"type" => "text",
		"defaultValue" => esc_html__("", 'compactor'),
		"parentSection" => "General Settings",
		"group" => "Site data",
		"description" => esc_html__("Add contact phone number", 'compactor'),
	),
	array(
		"label" => esc_html__("Working Time", 'compactor'),
		"id" => "head_info_time",
		"type" => "text",
		"defaultValue" => esc_html__("", 'compactor'),
		"parentSection" => "General Settings",
		"group" => "Site data",
		"description" => esc_html__("Add contact phone number", 'compactor'),
	),
	array(
		"label" => esc_html__("Call Us Today", 'compactor'),
		"id" => "head_info_phone",
		"type" => "text",
		"defaultValue" => esc_html__("", 'compactor'),
		"parentSection" => "General Settings",
		"group" => "Site data",
		"description" => esc_html__("Add contact phone number", 'compactor'),
	),
);